"""add daily bonus fields to user

Revision ID: cfd2c0a905bd
Revises: e55bc73451cb
Create Date: 2026-03-04 21:01:01.717488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision: str = "cfd2c0a905bd"
down_revision: Union[str, None] = "e55bc73451cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_daily_bonus", sa.DateTime(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "daily_bonus_streak", sa.Integer(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "daily_bonus_streak")
    op.drop_column("users", "last_daily_bonus")
    # ### end Alembic commands ###
